'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.view': 'View',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.role': 'Role',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.location': 'Location',
    'common.description': 'Description',
    'common.category': 'Category',
    'common.quantity': 'Quantity',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signOut': 'Sign Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.signingIn': 'Signing in...',
    'auth.welcome': 'Welcome to GESWORX!',
    'auth.invalidCredentials': 'Invalid credentials. Please try again.',
    'auth.loginFailed': 'Login failed. Please try again.',
    'auth.enterCredentials': 'Enter your credentials to access your workspace',
    'auth.demoCredentials': 'Demo Credentials',
    'auth.useCredentials': 'Use credentials',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.todayActivity': "Here's what's happening in your warehouse today.",
    'dashboard.overview': 'Dashboard Overview',
    'dashboard.userManagement': 'User Management',
    'dashboard.vanManagement': 'Van Management',
    'dashboard.materialManagement': 'Material Management',
    'dashboard.taskCalendar': 'Task Calendar',
    'dashboard.qrScanner': 'QR Code Scanner',
    'dashboard.vanLoading': 'Van Loading',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.fleetStatus': 'Fleet Status',
    'dashboard.yourAssignedVan': 'Your Assigned Van',
    
    // Users
    'users.title': 'User Management',
    'users.subtitle': 'Manage system users and their permissions',
    'users.addUser': 'Add User',
    'users.totalUsers': 'Total Users',
    'users.activeUsers': 'Active Users',
    'users.assignedVans': 'Assigned Vans',
    'users.allUsers': 'All Users',
    'users.manageAccounts': 'Manage user accounts and permissions',
    'users.assignedTo': 'Assigned to',
    'users.lastLogin': 'Last login',
    'users.editUser': 'Edit User',
    'users.deleteUser': 'Delete User',
    'users.inactive': 'Inactive',
    'users.createUser': 'Create New User',
    'users.editUserTitle': 'Edit User',
    'users.selectRole': 'Select role',
    'users.selectVan': 'Select van (optional)',
    'users.userCreated': 'User created successfully',
    'users.userUpdated': 'User updated successfully',
    'users.userDeleted': 'User deleted successfully',
    'users.confirmDelete': 'Are you sure you want to delete this user?',
    'users.deleteWarning': 'This action cannot be undone.',
    
    // Vans
    'vans.title': 'Van Management',
    'vans.subtitle': 'Manage fleet vehicles and their assignments',
    'vans.addVan': 'Add Van',
    'vans.totalFleet': 'Total Fleet',
    'vans.activeVans': 'Active Vans',
    'vans.inMaintenance': 'In Maintenance',
    'vans.fleetUtilization': 'Fleet Utilization',
    'vans.licensePlate': 'License Plate',
    'vans.assignedTo': 'Assigned to',
    'vans.loadCapacity': 'Load capacity',
    'vans.loadedMaterials': 'Loaded Materials',
    'vans.nextMaintenance': 'Next maintenance',
    'vans.scanMaterials': 'Scan Materials',
    'vans.assignUser': 'Assign User',
    'vans.scheduleMaintenance': 'Schedule Maintenance',
    'vans.createVan': 'Create New Van',
    'vans.editVan': 'Edit Van',
    'vans.enterLicensePlate': 'Enter license plate',
    'vans.selectUser': 'Select user (optional)',
    'vans.vanCreated': 'Van created successfully',
    'vans.vanUpdated': 'Van updated successfully',
    'vans.vanDeleted': 'Van deleted successfully',
    'vans.confirmDelete': 'Are you sure you want to delete this van?',
    'vans.active': 'Active',
    'vans.maintenance': 'Maintenance',
    'vans.inactive': 'Inactive',
    
    // Materials
    'materials.title': 'Material Management',
    'materials.subtitle': 'Track and manage materials with QR codes',
    'materials.addMaterial': 'Add Material',
    'materials.available': 'Available',
    'materials.loadedInVans': 'Loaded in Vans',
    'materials.inUse': 'In Use',
    'materials.containers': 'Containers',
    'materials.searchMaterials': 'Search materials or QR codes...',
    'materials.allCategories': 'All Categories',
    'materials.showQRCode': 'Show QR Code',
    'materials.assignToVan': 'Assign to Van',
    'materials.contents': 'Contents',
    'materials.lastScanned': 'Last scanned',
    'materials.createMaterial': 'Create New Material',
    'materials.editMaterial': 'Edit Material',
    'materials.materialName': 'Material Name',
    'materials.enterMaterialName': 'Enter material name',
    'materials.subcategory': 'Subcategory',
    'materials.enterSubcategory': 'Enter subcategory',
    'materials.enterQuantity': 'Enter quantity',
    'materials.isContainer': 'Is Container',
    'materials.containerDescription': 'Check if this material can contain other materials',
    'materials.materialCreated': 'Material created successfully',
    'materials.materialUpdated': 'Material updated successfully',
    'materials.materialDeleted': 'Material deleted successfully',
    'materials.confirmDelete': 'Are you sure you want to delete this material?',
    'materials.qrCodeTitle': 'QR Code',
    'materials.download': 'Download',
    'materials.print': 'Print',
    'materials.qrInstructions1': 'Scan this QR code to quickly identify and track this material.',
    'materials.qrInstructions2': 'Use your mobile device or QR scanner to load/unload materials.',
    
    // Calendar
    'calendar.title': 'Task Calendar',
    'calendar.subtitle': 'Your assigned tasks and schedule',
    'calendar.subtitleAdmin': 'Manage team tasks and assignments',
    'calendar.addTask': 'Add Task',
    'calendar.tasksFor': 'Tasks for',
    'calendar.tasksScheduled': 'tasks scheduled',
    'calendar.noTasks': 'No tasks scheduled for this date',
    'calendar.scheduled': 'Scheduled',
    'calendar.inProgress': 'In Progress',
    'calendar.completed': 'Completed',
    'calendar.highPriority': 'High Priority',
    'calendar.createTask': 'Create New Task',
    'calendar.editTask': 'Edit Task',
    'calendar.taskTitle': 'Task Title',
    'calendar.enterTaskTitle': 'Enter task title',
    'calendar.enterDescription': 'Enter task description',
    'calendar.startTime': 'Start Time',
    'calendar.endTime': 'End Time',
    'calendar.assignedUser': 'Assigned User',
    'calendar.priority': 'Priority',
    'calendar.low': 'Low',
    'calendar.medium': 'Medium',
    'calendar.high': 'High',
    'calendar.taskCreated': 'Task created successfully',
    'calendar.taskUpdated': 'Task updated successfully',
    'calendar.taskDeleted': 'Task deleted successfully',
    'calendar.confirmDelete': 'Are you sure you want to delete this task?',
    
    // QR Scanner
    'scanner.title': 'QR Code Scanner',
    'scanner.subtitle': 'Scan materials for loading and unloading',
    'scanner.cameraScanner': 'Camera Scanner',
    'scanner.useCameraOrManual': 'Use camera or manual input to scan materials',
    'scanner.startCamera': 'Start Camera Scanner',
    'scanner.stopScanner': 'Stop Scanner',
    'scanner.simulateScan': 'Simulate Scan',
    'scanner.manualInput': 'Manual Input',
    'scanner.qrCode': 'QR Code',
    'scanner.enterQRCode': 'Enter QR code (e.g., MAT-001)',
    'scanner.targetVan': 'Target Van (for loading)',
    'scanner.selectVan': 'Select a van...',
    'scanner.loadMaterial': 'Load Material',
    'scanner.unloadMaterial': 'Unload Material',
    'scanner.scanHistory': 'Scan History',
    'scanner.recentScans': 'Recent QR code scans and actions',
    'scanner.noScans': 'No scans yet',
    'scanner.startScanning': 'Start scanning materials to see history',
    'scanner.quickActions': 'Quick Actions',
    'scanner.commonQRCodes': 'Common QR codes for testing',
    'scanner.cameraStarted': 'Camera started. Point at a QR code to scan.',
    'scanner.cameraAccessDenied': 'Camera access denied. Please use manual input.',
    'scanner.enterQRCodeError': 'Please enter a QR code',
    'scanner.selectVanError': 'Please select a van for loading',
    'scanner.materialLoaded': 'loaded to van',
    'scanner.materialUnloaded': 'unloaded from van',
    'scanner.materialNotFound': 'Material not found in database',
    'scanner.qrCodeEntered': 'QR code entered',
    
    // Roles
    'roles.superAdmin': 'Super Admin',
    'roles.admin': 'Admin',
    'roles.user': 'User',
  },
  pt: {
    // Common
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.add': 'Adicionar',
    'common.search': 'Pesquisar',
    'common.loading': 'Carregando...',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.close': 'Fechar',
    'common.view': 'Visualizar',
    'common.actions': 'Ações',
    'common.status': 'Status',
    'common.name': 'Nome',
    'common.email': 'Email',
    'common.role': 'Função',
    'common.date': 'Data',
    'common.time': 'Hora',
    'common.location': 'Localização',
    'common.description': 'Descrição',
    'common.category': 'Categoria',
    'common.quantity': 'Quantidade',
    
    // Auth
    'auth.signIn': 'Entrar',
    'auth.signOut': 'Sair',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.enterEmail': 'Digite seu email',
    'auth.enterPassword': 'Digite sua senha',
    'auth.signingIn': 'Entrando...',
    'auth.welcome': 'Bem-vindo ao GESWORX!',
    'auth.invalidCredentials': 'Credenciais inválidas. Tente novamente.',
    'auth.loginFailed': 'Falha no login. Tente novamente.',
    'auth.enterCredentials': 'Digite suas credenciais para acessar seu espaço de trabalho',
    'auth.demoCredentials': 'Credenciais de Demonstração',
    'auth.useCredentials': 'Usar credenciais',
    
    // Dashboard
    'dashboard.welcome': 'Bem-vindo de volta',
    'dashboard.todayActivity': 'Aqui está o que está acontecendo em seu armazém hoje.',
    'dashboard.overview': 'Visão Geral do Painel',
    'dashboard.userManagement': 'Gerenciamento de Usuários',
    'dashboard.vanManagement': 'Gerenciamento de Vans',
    'dashboard.materialManagement': 'Gerenciamento de Materiais',
    'dashboard.taskCalendar': 'Calendário de Tarefas',
    'dashboard.qrScanner': 'Scanner de Código QR',
    'dashboard.vanLoading': 'Carregamento de Van',
    'dashboard.recentActivity': 'Atividade Recente',
    'dashboard.fleetStatus': 'Status da Frota',
    'dashboard.yourAssignedVan': 'Sua Van Designada',
    
    // Users
    'users.title': 'Gerenciamento de Usuários',
    'users.subtitle': 'Gerencie usuários do sistema e suas permissões',
    'users.addUser': 'Adicionar Usuário',
    'users.totalUsers': 'Total de Usuários',
    'users.activeUsers': 'Usuários Ativos',
    'users.assignedVans': 'Vans Designadas',
    'users.allUsers': 'Todos os Usuários',
    'users.manageAccounts': 'Gerencie contas de usuário e permissões',
    'users.assignedTo': 'Designado para',
    'users.lastLogin': 'Último login',
    'users.editUser': 'Editar Usuário',
    'users.deleteUser': 'Excluir Usuário',
    'users.inactive': 'Inativo',
    'users.createUser': 'Criar Novo Usuário',
    'users.editUserTitle': 'Editar Usuário',
    'users.selectRole': 'Selecionar função',
    'users.selectVan': 'Selecionar van (opcional)',
    'users.userCreated': 'Usuário criado com sucesso',
    'users.userUpdated': 'Usuário atualizado com sucesso',
    'users.userDeleted': 'Usuário excluído com sucesso',
    'users.confirmDelete': 'Tem certeza de que deseja excluir este usuário?',
    'users.deleteWarning': 'Esta ação não pode ser desfeita.',
    
    // Vans
    'vans.title': 'Gerenciamento de Vans',
    'vans.subtitle': 'Gerencie veículos da frota e suas designações',
    'vans.addVan': 'Adicionar Van',
    'vans.totalFleet': 'Frota Total',
    'vans.activeVans': 'Vans Ativas',
    'vans.inMaintenance': 'Em Manutenção',
    'vans.fleetUtilization': 'Utilização da Frota',
    'vans.licensePlate': 'Placa',
    'vans.assignedTo': 'Designado para',
    'vans.loadCapacity': 'Capacidade de carga',
    'vans.loadedMaterials': 'Materiais Carregados',
    'vans.nextMaintenance': 'Próxima manutenção',
    'vans.scanMaterials': 'Escanear Materiais',
    'vans.assignUser': 'Designar Usuário',
    'vans.scheduleMaintenance': 'Agendar Manutenção',
    'vans.createVan': 'Criar Nova Van',
    'vans.editVan': 'Editar Van',
    'vans.enterLicensePlate': 'Digite a placa',
    'vans.selectUser': 'Selecionar usuário (opcional)',
    'vans.vanCreated': 'Van criada com sucesso',
    'vans.vanUpdated': 'Van atualizada com sucesso',
    'vans.vanDeleted': 'Van excluída com sucesso',
    'vans.confirmDelete': 'Tem certeza de que deseja excluir esta van?',
    'vans.active': 'Ativa',
    'vans.maintenance': 'Manutenção',
    'vans.inactive': 'Inativa',
    
    // Materials
    'materials.title': 'Gerenciamento de Materiais',
    'materials.subtitle': 'Rastreie e gerencie materiais com códigos QR',
    'materials.addMaterial': 'Adicionar Material',
    'materials.available': 'Disponível',
    'materials.loadedInVans': 'Carregado em Vans',
    'materials.inUse': 'Em Uso',
    'materials.containers': 'Contêineres',
    'materials.searchMaterials': 'Pesquisar materiais ou códigos QR...',
    'materials.allCategories': 'Todas as Categorias',
    'materials.showQRCode': 'Mostrar Código QR',
    'materials.assignToVan': 'Designar para Van',
    'materials.contents': 'Conteúdo',
    'materials.lastScanned': 'Último escaneamento',
    'materials.createMaterial': 'Criar Novo Material',
    'materials.editMaterial': 'Editar Material',
    'materials.materialName': 'Nome do Material',
    'materials.enterMaterialName': 'Digite o nome do material',
    'materials.subcategory': 'Subcategoria',
    'materials.enterSubcategory': 'Digite a subcategoria',
    'materials.enterQuantity': 'Digite a quantidade',
    'materials.isContainer': 'É Contêiner',
    'materials.containerDescription': 'Marque se este material pode conter outros materiais',
    'materials.materialCreated': 'Material criado com sucesso',
    'materials.materialUpdated': 'Material atualizado com sucesso',
    'materials.materialDeleted': 'Material excluído com sucesso',
    'materials.confirmDelete': 'Tem certeza de que deseja excluir este material?',
    'materials.qrCodeTitle': 'Código QR',
    'materials.download': 'Baixar',
    'materials.print': 'Imprimir',
    'materials.qrInstructions1': 'Escaneie este código QR para identificar e rastrear rapidamente este material.',
    'materials.qrInstructions2': 'Use seu dispositivo móvel ou scanner QR para carregar/descarregar materiais.',
    
    // Calendar
    'calendar.title': 'Calendário de Tarefas',
    'calendar.subtitle': 'Suas tarefas designadas e cronograma',
    'calendar.subtitleAdmin': 'Gerencie tarefas da equipe e designações',
    'calendar.addTask': 'Adicionar Tarefa',
    'calendar.tasksFor': 'Tarefas para',
    'calendar.tasksScheduled': 'tarefas agendadas',
    'calendar.noTasks': 'Nenhuma tarefa agendada para esta data',
    'calendar.scheduled': 'Agendado',
    'calendar.inProgress': 'Em Andamento',
    'calendar.completed': 'Concluído',
    'calendar.highPriority': 'Alta Prioridade',
    'calendar.createTask': 'Criar Nova Tarefa',
    'calendar.editTask': 'Editar Tarefa',
    'calendar.taskTitle': 'Título da Tarefa',
    'calendar.enterTaskTitle': 'Digite o título da tarefa',
    'calendar.enterDescription': 'Digite a descrição',
    'calendar.startTime': 'Hora de Início',
    'calendar.endTime': 'Hora de Término',
    'calendar.assignedUser': 'Usuário Designado',
    'calendar.priority': 'Prioridade',
    'calendar.low': 'Baixa',
    'calendar.medium': 'Média',
    'calendar.high': 'Alta',
    'calendar.taskCreated': 'Tarefa criada com sucesso',
    'calendar.taskUpdated': 'Tarefa atualizada com sucesso',
    'calendar.taskDeleted': 'Tarefa excluída com sucesso',
    'calendar.confirmDelete': 'Tem certeza de que deseja excluir esta tarefa?',
    
    // QR Scanner
    'scanner.title': 'Scanner de Código QR',
    'scanner.subtitle': 'Escaneie materiais para carregamento e descarregamento',
    'scanner.cameraScanner': 'Scanner de Câmera',
    'scanner.useCameraOrManual': 'Use câmera ou entrada manual para escanear materiais',
    'scanner.startCamera': 'Iniciar Scanner de Câmera',
    'scanner.stopScanner': 'Parar Scanner',
    'scanner.simulateScan': 'Simular Escaneamento',
    'scanner.manualInput': 'Entrada Manual',
    'scanner.qrCode': 'Código QR',
    'scanner.enterQRCode': 'Digite o código QR (ex: MAT-001)',
    'scanner.targetVan': 'Van de Destino (para carregamento)',
    'scanner.selectVan': 'Selecionar uma van...',
    'scanner.loadMaterial': 'Carregar Material',
    'scanner.unloadMaterial': 'Descarregar Material',
    'scanner.scanHistory': 'Histórico de Escaneamento',
    'scanner.recentScans': 'Escaneamentos recentes de código QR e ações',
    'scanner.noScans': 'Nenhum escaneamento ainda',
    'scanner.startScanning': 'Comece a escanear materiais para ver o histórico',
    'scanner.quickActions': 'Ações Rápidas',
    'scanner.commonQRCodes': 'Códigos QR comuns para teste',
    'scanner.cameraStarted': 'Câmera iniciada. Aponte para um código QR para escanear.',
    'scanner.cameraAccessDenied': 'Acesso à câmera negado. Use entrada manual.',
    'scanner.enterQRCodeError': 'Por favor, digite um código QR',
    'scanner.selectVanError': 'Por favor, selecione uma van para carregamento',
    'scanner.materialLoaded': 'carregado na van',
    'scanner.materialUnloaded': 'descarregado da van',
    'scanner.materialNotFound': 'Material não encontrado no banco de dados',
    'scanner.qrCodeEntered': 'Código QR inserido',
    
    // Roles
    'roles.superAdmin': 'Super Admin',
    'roles.admin': 'Admin',
    'roles.user': 'Usuário',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const storedLanguage = localStorage.getItem('gesworx_language') as Language;
    if (storedLanguage && (storedLanguage === 'en' || storedLanguage === 'pt')) {
      setLanguage(storedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('gesworx_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);